version: "3.5"
services:
  sso:
    build:
      context: ../.
    restart: unless-stopped
    ports:
      - "44044:44044"
      - "8000:8000"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

volumes:
  kafka_0_data:
  kafka_1_data:
  kafka_2_data: