definitions:
  v1.Login:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  v1.Response:
    properties:
      access_token:
        type: string
      error:
        type: string
      refresh_token:
        type: string
      status:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    name: API Support
  description: sso service.
  license:
    name: Apache 2.0
  title: Swagger API
  version: "1.0"
paths:
  /auth/healthz:
    get:
      description: Определяет, нужно ли перезагрузить сервис
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Проверка, что приложение живо
      tags:
      - Health
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns access and refresh tokens.
      parameters:
      - description: Login request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/v1.Login'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/v1.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.Response'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Login
      tags:
      - Auth
  /auth/ready:
    get:
      description: Определяет можно ли подавать трафик на сервис
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Проверка готовности приложения
      tags:
      - Health
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
