definitions:
  v1.Response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    name: API Support
  description: sso service.
  license:
    name: Apache 2.0
  title: Swagger API
  version: "1.0"
paths:
  /auth/ready:
    get:
      description: Определяет можно ли подавать трафик на сервис
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Проверка готовности приложения
      tags:
      - Health
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
