# See: https://taskfile.dev/api/

version: "3"

tasks:
  grpc:
    aliases:
      - grpc
    desc: "Generate code from proto files to grpc"
    cmds:
      - protoc -I proto proto/sso/sso.proto --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative
      - mv sso/* proto/sso/gen
      - rm -r sso
  kafka-data-v1:
    aliases:
      - proto
    desc: "Generate code from proto files for kafka"
    cmds:
      - protoc -I proto proto/registration.v1/registration.proto --go_out=proto/registration.v1/ --go_opt=paths=source_relative --go-grpc_out=proto/registration.v1/ --go-grpc_opt=paths=source_relative
  swagger:
    aliases:
      - swag
    desc: "Generate code from proto files for kafka"
    cmds:
      - cd .. && swag init -g ./cmd/sso/main.go -o ./cmd/sso/docs
  migrate:
    aliases:
      - migrate
    desc: "Generate code from proto files for kafka"
    cmds:
      - cd .. && go run ./cmd/migrator/postgres  --p ./migrations -d postgres://postgres:postgres@localhost:5000/postgres?sslmode=disable