# See: https://taskfile.dev/api/

version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./sso/gen/go/ --go_opt=paths=source_relative --go-grpc_out=./sso/gen/go/ --go-grpc_opt=paths=source_relative

